# docker-compose -f docker-compose-local.yml up -d

services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: inusidian-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: inusidian
    ports:
      - "3366:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
volumes:
  db_data:
