services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: inusidian
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always
    networks:
      - default
networks:
  default:
