services:
  #  DBコンテナ
  mysql:
    image: mysql:8.4
    platform: linux/amd64
    container_name: inusidian-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - ./database:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: "mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e 'SHOW DATABASES;'"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Flyway
  flyway:
    image: ${DOCKER_REGISTRY}/inusidian:flyway-${FLYWAY_VERSION}
    command: ["migrate"]
    environment:
      FLYWAY_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - migration

  #  APIコンテナ
  inusidian-api:
    image: ${DOCKER_REGISTRY}/inusidian:api-${API_VERSION}
    container_name: inusidian-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      AUTH0_ISSUER: ${AUTH0_ISSUER}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    command: java -jar /app/inusidian-api.jar
    healthcheck:
      test: "nc -zv localhost 8080"
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s
    depends_on:
      mysql:
        condition: service_healthy

  #  フロントコンテナ
  inusidian-web:
    image: ${DOCKER_REGISTRY}/inusidian:web-${WEB_VERSION}
    container_name: inusidian-web
    ports:
      - "3000:3000"
    depends_on:
      inusidian-api:
        condition: service_healthy
